# Generated by Django 3.1.2 on 2020-11-22 16:22

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('beer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('kor_name', models.CharField(max_length=100)),
                ('eng_name', models.CharField(max_length=100)),
                ('kor_company_name', models.CharField(max_length=100)),
                ('eng_company_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('country_code', models.CharField(max_length=200, null=True)),
                ('country_name', models.CharField(max_length=200, null=True)),
                ('alcohol', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, storage=api.models.OverwriteStorage(), upload_to='beer')),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('total_rate', models.CharField(default='0.0', max_length=100)),
            ],
            options={
                'db_table': 'Beer',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('rate', models.IntegerField(null=True)),
                ('total_like', models.IntegerField(default=0)),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.beer')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('profile', models.ImageField(null=True, storage=api.models.OverwriteStorage(), upload_to=api.models.profile_path)),
                ('profile_url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('review_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_like', to='api.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_like', to='api.user')),
            ],
            options={
                'db_table': 'ReviewLike',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.user'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=5000)),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.beer')),
            ],
            options={
                'db_table': 'Ingredient',
            },
        ),
        migrations.CreateModel(
            name='BeerLike',
            fields=[
                ('beer_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_like', to='api.beer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_like', to='api.user')),
            ],
            options={
                'db_table': 'BeerLike',
            },
        ),
    ]
