# Generated by Django 3.1.2 on 2020-10-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='beer',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
