# Generated by Django 3.1.2 on 2020-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='imagefile',
            field=models.FileField(null=True, upload_to='imagefile/%Y/%m/%d'),
        ),
    ]
