# Generated by Django 3.1.2 on 2020-12-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='detail_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='beer',
            name='total_beer_like',
            field=models.IntegerField(default=0),
        ),
    ]
