# Generated by Django 3.1.2 on 2020-10-18 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201019_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('alcohol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('ingredient', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Beer',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
