# Generated by Django 3.1.2 on 2020-10-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201012_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='imagefile',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image',
            field=models.FileField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
