# Generated by Django 3.1.2 on 2020-10-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review_score'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
